# Generated by Django 3.2.9 on 2021-12-14 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AJiO', '0002_completedish_dish'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompleteDish',
        ),
    ]
